# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
        exclude: tests/mocks/*
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/Cretezy/flutter-format-pre-commit
    rev: "master"
    hooks:
      - id: flutter-format
